### ISSUE TITLE
这里是主页 css 改进的建议（附代码及对比图）

### ISSUE THREAD

**Issue by cornradio** [vastsa/FileCodeBox#146]
下面放两个对比图，如果觉得我这个样式更好看，可否考虑未来更新进来？

![Group 4](https://github.com/vastsa/FileCodeBox/assets/119606491/1000ac80-a308-4409-bf6a-15a1e31eade2)

![Group 5](https://github.com/vastsa/FileCodeBox/assets/119606491/72029378-f554-431b-94d0-accd5367cb33)

```CSS

/* 输入位置在电脑上看起来有些太大了,改小了一点 */
#app{
	transform: scale(.6);
	
}

/* 让 button 的间距保持一致,去掉丑陋边框,保持上下左右间距相等 */
.key-button {
    width: 6rem;
    height: 6rem;
    margin: 0.8rem;
	  border: 0;

}
/* 增加一点点 点击动画 */
.key-button:active{
	transform: scale(.9);
}
/* 输入取件码 位置 */
.el-col-24 {
    max-width: 92%;
    margin: auto;
	margin-bottom: 1.5em;
}
/* 输入码-输入框样式 对齐位置和阴影 */
.el-input__wrapper {
background-color: #97969638;
	box-shadow: inset 0 0 10px #0000007a ;
}
/* 输入框内部 文字均匀分布且留有空间 */
.el-input__wrapper input{
	margin: 20px;
	align-self: center;
	letter-spacing: .9em;
	font-family: monospace;
}

/* 删除主页左上角冗余的按钮 */
.red{
	display: none;
}
.green{
	display: none;
}
```
