### ISSUE TITLE
关闭游客上传功能，但没有任何效果

### ISSUE THREAD

**Issue by shakenny** [vastsa/FileCodeBox#161]
我用docker-compose布署了FileCodeBox，当我去后台设置，配置“开启上传”：“关闭游客上传”后，发现前端页面仍然可以不受限制去上传文件。是这样的吗？

<img width="470" alt="截屏2024-05-12 19 33 59" src="https://github.com/vastsa/FileCodeBox/assets/45874689/a263896a-d4dc-45b4-bfff-f63cd5fe55f0">

另附上docker-compose.yml原文：

```
name: filecodebox
services:
    filecodebox:
      image: lanol/filecodebox:beta
      container_name: filecodebox
      restart: always
      ports:
        - 5333:12345
      volumes:
        - /home/ext_disk1/filecodebox/data:/app/data
```
